### ISSUE TITLE
ad.guideinchina.com 登陆问题

### ISSUE THREAD

**Issue by arlum** [UReact/AD_feedback#1]
首先，第一次将http://test.ad.guideinchina.com 复制到浏览器的时候是可以扫到二维码的。
但扫完点登录之后，就变成了《500》的错误，点back to home没反应；重新加载原网址就出现《403》；重复。

![1](https://user-images.githubusercontent.com/47769588/53327535-f2ff4e00-3922-11e9-8492-f3aaadd4d4df.png)
![2](https://user-images.githubusercontent.com/47769588/53327537-f2ff4e00-3922-11e9-832a-de55c8a4a08e.png)

**Comment by jimmywong123** [comment]
已经修复，现在登录进来不会再报错。
