### ISSUE TITLE
新建广告&点击url跳不到对应地址&首页

### ISSUE THREAD

**Issue by OwEeicebare** [UReact/AD_feedback#2]
**新建广告:**

1. 在accountpersonal与enterprise没有通过验证的时候可以新建广告
2.新建广告的时候url地址可以写中文或者数字,
3.金额可以加入中英文提交
4.新建广告有时金额在主页显示不出来需要点击修改竞价后才正常显示

**url跳不到对应地址:**
`<Row className={styles.website}>url:&nbsp;<a href={record.redirectUrl} target='_blank' rel="noopener noreferrer" style={{color:'rgba(0,0,0,.65)'}}>{record.redirectUrl}</a></Row>`
**首页新建出的问题广告**
![default](https://user-images.githubusercontent.com/42399003/53330172-cd754300-3928-11e9-9fa6-0661e61074e1.jpg)

**删除功能**
广告删除

**Comment by OwEeicebare** [comment]
![default](https://user-images.githubusercontent.com/42399003/53330136-b5052880-3928-11e9-8e05-e5a9d4f74915.jpg)

**Comment by jimmywong123** [comment]
1，暂时忽略
2，url很复杂，很难用正则控制，暂时不对url验证。
3，金额虽然可以输入中文，但在失去焦点时会自动清空。还是只能输入数字。
4，现在金额已绑定到竞价表，ad的paidperday是显示的每天消费的。
5，url会跳转到广告地址。
